### ISSUE TITLE
Image preview is disabled

### ISSUE THREAD

**Issue by alokdhir** [lusingander/stu#60]
why?

**Comment by lusingander** [comment]
Yes, image previews are disabled by default and you need to configure the following in [config.toml](https://github.com/lusingander/stu?tab=readme-ov-file#config):

```toml
[preview]
image = true
```
